


import type {  MapperMarket } from '../interfaces/MarketMapper';

import { all } from '../axios/AxiosGetAll';
import type { MarketData } from '../interfaces/MarketInterface';

export const MarketResponse =async  ():Promise<MapperMarket[]>  => {

    const response = await all<MarketData>({});
    
       

        

   
    return  response.data.data.map((value) => ({
        open: value.open,
        high: value.high,
        low: value.low,
        close: value.close,
        asset_type:value.asset_type
    }))
    
}
/**
 * stdout
 * This file has been autogenerated using quicktype https://github.com/quicktype/quicktype - DO NOT EDIT
 * This file depends of https://github.com/DaveGamble/cJSON, https://github.com/joelguittet/c-list and https://github.com/joelguittet/c-hashtable
 * To parse json data from json string use the following: struct <type> * data = cJSON_Parse<type>(<string>);
 * To get json data from cJSON object use the following: struct <type> * data = cJSON_Get<type>Value(<cjson>);
 * To get cJSON object from json data use the following: cJSON * cjson = cJSON_Create<type>(<data>);
 * To print json string from json data use the following: char * string = cJSON_Print<type>(<data>);
 * To delete json data use the following: cJSON_Delete<type>(<data>);
 */

